// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbiAwfMUmlJEPPICiwWzsWTGXDxGL1BpM',
    appId: '1:354953703552:web:535914e5f2f66b6c4a7665',
    messagingSenderId: '354953703552',
    projectId: 'fir-502de',
    authDomain: 'fir-502de.firebaseapp.com',
    storageBucket: 'fir-502de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC78zqywIXlN0uzlkUE9bSieN4z12gmL2c',
    appId: '1:354953703552:android:7b6d5411992ecf154a7665',
    messagingSenderId: '354953703552',
    projectId: 'fir-502de',
    storageBucket: 'fir-502de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgWqQ5jLjTLxKX_kRBlboQpysrCiXI2ns',
    appId: '1:354953703552:ios:897231f52d8054224a7665',
    messagingSenderId: '354953703552',
    projectId: 'fir-502de',
    storageBucket: 'fir-502de.appspot.com',
    iosBundleId: 'com.example.amazon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgWqQ5jLjTLxKX_kRBlboQpysrCiXI2ns',
    appId: '1:354953703552:ios:5226c3d537127f2a4a7665',
    messagingSenderId: '354953703552',
    projectId: 'fir-502de',
    storageBucket: 'fir-502de.appspot.com',
    iosBundleId: 'com.example.amazon.RunnerTests',
  );
}
